add Criterion.relatedLots field and update changelog in README.me
open-contracting-extensions/ocds_requirements_extension pull request #33
Opened 2022-04-01 12:06 UTC by odscjen

in the description I've copied from the relatedLots descriptions in the lots extension. But these read as directed to the publisher which goes against the schema style guide. An alternative could be "The identifiers of related lots that this criterion applies to." which is in more of a neutral voice.

2022-04-01 15:21 UTC, jpmckinney commented
Yes, let's use a neutral voice. Happy to then replicate the change to other extensions.

2022-04-01 15:33 UTC, odscjen commented
sounds good, I've updated the description accordingly. I'll create an issue for updating the language in the lots extension

2022-04-03 21:59 UTC, duncandewhurst requested changes
Happy for you to request a review from @jpmckinney once my suggestion is committed.

2022-04-03 21:59 UTC, duncandewhurst commented on README.md
> +This extension was originally discussed in <https://github.com/open-contracting/ocds-extensions/issues/76>.
We usually only include this sentence to reference discussions that happened prior to the initial version of the extension. Discussions about subsequent changes are linked from the pull requests so we don't need to link them in the changelog.

```suggestion
```

2022-04-04 22:20 UTC, jpmckinney commented on release-schema.json
> +          "title": " Related lot(s)",
Extra whitespace

```suggestion
          "title": "Related lot(s)",
```

2022-04-04 22:20 UTC, jpmckinney commented on release-schema.json
> +          "description": "The identifiers of related lots that this criterion applies to.",
Avoid preposition-stranding, unless it were to make the phrase harder to read (e.g. "a grammatical style up with which I will not put").

```suggestion
          "description": "The identifiers of the lots to which this criterion applies.",
```

2022-04-04 22:21 UTC, merged

2022-04-04 22:24 UTC, jpmckinney commented
@odscjen When creating a pull request that closes an issue, please follow this guidance, so that the PR is linked to the issue, and so that it also closes it when merged: https://ocp-software-handbook.readthedocs.io/en/latest/github/developers.html#automatically-with-pull-requests